typedef enum {
// auto-generated: operators enum - begin
  MUD_OP_ARITHMETIC_ADDING = 200,
  MUD_OP_ARITHMETIC_SUBTRACTING = 201,
  MUD_OP_ARITHMETIC_MULTIPLYING = 202,
  MUD_OP_ARITHMETIC_DIVIDING = 203,
  MUD_OP_ARITHMETIC_REMAINDER = 204,
  MUD_OP_ARITHMETIC_POW = 205,
  MUD_OP_ARITHMETIC_LOG = 206,
  MUD_OP_STRING_CONCAT = 300,
  MUD_OP_STRING_FORMAT = 301
// auto-generated: operators enum - end
} mud_operator_e;
